name: .NET

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]  # triggers on version tags like v1.2.3
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Extract version from tag
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Pack with version
      run: dotnet pack --configuration Release /p:Version=${{ steps.get_version.outputs.version }} --output ./nupkg

    - name: Upload NuGet package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: nuget-packages
        path: ./nupkg/*.nupkg

    - name: Publish to NuGet
      run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: true
        prerelease: false
        generate_release_notes: true

    - name: Upload NuGet package to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nupkg/*.nupkg
        asset_name: Wren.NET.${{ steps.get_version.outputs.version }}.nupkg
        asset_content_type: application/octet-stream
